### ISSUE TITLE
PDRatingView#ItemPadding

### ISSUE THREAD

**Issue by qqilihq** [patridge/PDRating#2]
Hi there,

I'm using PDRating in my Xamarin app, and it saved me quite some time. Thank you! However, I am having one issue:

* The `ItemPadding` property (which is mentioned on the Github project page), is not available
* Maybe related to this problem, but not sure: The namespace `PatridgeDev` is not available, instead I had to use `PDRatingSample`, which seems a little odd

Am I doing something wrong? Checked in my Xamarin project, I am using PDReview 2.0.1 which seems to be the current one.

**Comment by patridge** [comment]
Thanks for letting me know about the issues you are running into. I'll try to look into the problem more tonight. It definitely looks like I didn't catch something I messed up in the latest version. The namespaces did indeed get messed up. It appears that I renamed all of the namespaces to `PDRatingSample`, so I'm hoping it will be a simple fix. After I resolve the namespace issue, I'll see what's going on with `ItemPadding` giving you trouble.

**Comment by qqilihq** [comment]
Hey Adam, thanks a bunch for getting back! In the meantime, I found out, that the `ItemPadding` property is not in the `PDRatingView` class, but in `RatingConfig`. So I guess it's sufficient to update the GitHub documentation :)

Still looking forward to your feedback concerning the namespace.

**Comment by patridge** [comment]
Judging from my repo history, the namespace and the docs were messed up from the very beginning. I owe you an apology on that one. I guess this is what happens when you end up not using your own component anymore. I created spun this component off from a project that ended up not seeing the light of day.

**Comment by patridge** [comment]
I'll see if I can get a new version submitted to Xamarin Components yet tonight, but they sometimes take a little bit to go through. You can certainly use the source directly from here, though, if that helps get you rolling.

**Comment by qqilihq** [comment]
Cool, thank you!

**Comment by patridge** [comment]
Thank you so much for filing this issue. The new [v2.0.2 is live on Xamarin Components](https://components.xamarin.com/view/pdreview) with the namespace fix and docs fix.
