### ISSUE TITLE
Xamarin Components store will be shut down soon.

### ISSUE THREAD

**Issue by lvhtrong1793** [patridge/PDRating#5]
Hi develop team,

Microsoft has sent an email to me. By this email, Microsoft informs that Xamarin Component store will be shut down on May 15, 2018 and they suggest reference all libraries I used to NuGet instead of Xamarin Component store. But this component is not available on NuGet now. Please check and upload the current version to NuGet before Xamarin Component store is shut down completely.

Thank you so much and have a nice day.

**Comment by patridge** [comment]
Thank you for the reminder, @lvhtrong1793. I will make a note to migrate things to NuGet.

Out of curiosity, are you using this in a production app these days?

**Comment by patridge** [comment]
I've published it, as is, to NuGet as a package under the name RatingView. At some point, I want to remove the `PD` from the system, but I didn't want this transfer to be a change of any kind.

https://www.nuget.org/packages/RatingView/

You'll need to remove the old Xamarin Component version and then add it via NuGet to make the transition.

**Comment by lvhtrong1793** [comment]
Thank you very much.
