### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [patridge/PDRating#6]
Hello, I designed a logo for PDRating. I wanted to emphasize the '' rating '' feature by using the initials of the app and a star icon. If you like it, I will send you a pr. Or If you have another logo idea, you can tell me.

![rating](https://user-images.githubusercontent.com/36298335/39883823-9f38c494-5490-11e8-801b-5eea8596c906.jpg)

Readmefile view;

![view](https://user-images.githubusercontent.com/36298335/39883936-e7e252dc-5490-11e8-9515-dc655e410e31.png)

**Comment by patridge** [comment]
In the process of migrating to NuGet from the Xamarin Component Store, I forgot to set up the package's `iconUrl` metadata. I've set up a [64x64 icon](https://github.com/patridge/PDRating/blob/master/component/icons/pdrating_64x64.png) and added it to the **.nuspec** file, per the [docs](https://docs.microsoft.com/en-us/nuget/reference/nuspec#single-elements), for the next package update. Thank you for the reminder.
